services:
  - type: web
    name: occu-med-global-address-geocoder
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m streamlit run main.py --server.address=0.0.0.0 --server.port=$PORT --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: GEOCODER_USER_AGENT
        value: OccuMedAddressGeocoder/1.0
      - key: NOMINATIM_BASE_URL
        value: https://nominatim.openstreetmap.org/search
