services:
  - type: web
    name: occu-med-global-address-geocoder
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: GEOCODER_USER_AGENT
        value: OccuMedAddressGeocoder/1.0
      - key: NOMINATIM_BASE_URL
        value: https://nominatim.openstreetmap.org/search
